import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { execFile } from "node:child_process"
import { promisify } from "node:util"
import { pathToFileURL, fileURLToPath } from "node:url"

const execFileP=promisify(execFile)
async function git(cwd,args){return execFileP("git",args,{cwd,encoding:"utf8"})}
async function copyTree(src,dst){await fs.cp(src,dst,{recursive:true})}

async function fixture({gitRepo=false}={}){
  const pluginDir=path.resolve(fileURLToPath(new URL("..",import.meta.url)))
  const temp=await fs.mkdtemp(path.join(os.tmpdir(),"ade-auth-toctou-"))
  const oldLocal=process.env.LOCALAPPDATA, oldXdg=process.env.XDG_STATE_HOME
  process.env.LOCALAPPDATA=path.join(temp,"localappdata");process.env.XDG_STATE_HOME=path.join(temp,"state")
  const runtime=path.join(temp,"plugin");await fs.mkdir(path.join(runtime,"src"),{recursive:true})
  await fs.copyFile(path.join(pluginDir,"src","index.ts"),path.join(runtime,"src","index.ts"));await fs.copyFile(path.join(pluginDir,"capabilities.json"),path.join(runtime,"capabilities.json"));await copyTree(path.join(pluginDir,"assets"),path.join(runtime,"assets"));await copyTree(path.join(pluginDir,"compat-runtime"),path.join(runtime,"compat-runtime"))
  const sdk=path.join(runtime,"node_modules","@opencode-ai","plugin");await fs.mkdir(sdk,{recursive:true});await fs.writeFile(path.join(sdk,"package.json"),JSON.stringify({name:"@opencode-ai/plugin",type:"module",exports:"./index.js"}));await fs.writeFile(path.join(sdk,"index.js"),"export const Plugin={define:(value)=>value}\n")
  const project=path.join(temp,"project");await fs.mkdir(path.join(project,".ai"),{recursive:true})
  const control={schema_version:3,work_item_id:"AUTH-HARDEN",profile:"STANDARD",revision:0,global_status:"NOT_DONE",product:{required:false,status:"DRAFT",revision:0},delivery:{required:false,status:"DRAFT",revision:0},engineering:{required:true,status:"DISCOVERING",revision:0},evidence:[],evidence_count:0,recent_handoffs:[],notes:[],work_management:{provider:"none",sync_status:"NOT_CONFIGURED",last_sync_at:"",external_refs:[]},traceability:{file:".ai/traceability.json"},audit:{file:".ai/audit.jsonl"}}
  await fs.writeFile(path.join(project,".ai","control.json"),JSON.stringify(control,null,2)+"\n")
  await fs.writeFile(path.join(project,".ai","tracker-policy.json"),JSON.stringify({schema_version:1,read:{authorized:true},write:{authorized:true},remote:{allowed_https_hosts:["api.github.com","api.linear.app"],allowed_github_repositories:["octo/repo"],allowed_github_projects:["octo/4","octo/5"],allowed_jira_projects:[],allowed_linear_team_ids:[]}},null,2)+"\n")
  await fs.writeFile(path.join(project,".ai","integrations.json"),JSON.stringify({schema_version:1,work_management:{provider:"github",github:{owner:"octo",repository:"repo",project_owner:"octo",project_number:4,connection_id:"github"}}},null,2)+"\n")
  await fs.writeFile(path.join(project,".ai","vcs-policy.json"),JSON.stringify({schema_version:1,authorized:true,protected_branches:["main"],stage:{allowed:true},commit:{allowed:true},push:{allowed:true,remote:"origin",allowed_remote_urls:[]},pull_request:{allowed:true,base_branch:"main",allowed_base_branches:["main","develop"],allowed_repositories:["octo/repo"]},hooks:{allow_bypass:false}},null,2)+"\n")
  await fs.writeFile(path.join(project,".ai","execution-policy.json"),JSON.stringify({schema_version:1,authorized:true,checks:{safe:{owner:"verifier",non_destructive:true,runner:"process",allow_host_process:true,executable:"node",arguments:["--version"],working_directory:".",allowed_exit_codes:[0],timeout_ms:5000}}},null,2)+"\n")
  if(gitRepo){await git(project,["init","-b","feature"]);await git(project,["config","user.email","test@example.invalid"]);await git(project,["config","user.name","ADE Test"]);await fs.writeFile(path.join(project,"app.txt"),"base\n");await git(project,["add","app.txt"]);await git(project,["commit","-m","base"])}
  return {temp,runtime,project,restoreEnv(){if(oldLocal===undefined)delete process.env.LOCALAPPDATA;else process.env.LOCALAPPDATA=oldLocal;if(oldXdg===undefined)delete process.env.XDG_STATE_HOME;else process.env.XDG_STATE_HOME=oldXdg}}
}
function makeContext(project,cap){const hooks={},tools=new Map(),commands=new Map(),synthetic=[];const agentRecords=Object.keys(cap.agents).map(id=>({id,description:id}));const locationInfo={directory:project,project:{id:"test",directory:project,canonical:project}};const ctx={app:{version:"beta-test"},location:{directory:path.dirname(project),project:{id:"host",directory:path.dirname(project),canonical:path.dirname(project)}},storage:{async set(){},async get(){},async remove(){},async scan(){return{entries:[]}}},agent:{async transform(cb){cb({get(id){return agentRecords.find(x=>x.id===id)},list(){return agentRecords},default(){},update(){},remove(){}})},async list(){return{location:locationInfo,data:agentRecords}}},skill:{async list(){return{location:locationInfo,data:[{id:"ai-driven-engineering"}]}}},plugin:{async list(){return{location:locationInfo,data:[{id:"ai-driven-engineering.native"}]}}},session:{async get({sessionID}){return{id:sessionID,location:{directory:project}}},async hook(name,cb){hooks[`session:${name}`]=cb},async synthetic(v){synthetic.push(v)},async prompt(){},async switchAgent(){},async context(){return[]}},permission:{async hook(name,cb){hooks[`permission:${name}`]=cb}},tool:{async transform(cb){cb({add(def){const ns=def.options?.namespace?`${def.options.namespace}_`:"";tools.set(`${ns}${def.name}`,def)},list(){return[...tools.values()]},get(id){return tools.get(id)},update(){},remove(id){tools.delete(id)}})}},command:{async transform(cb){cb({add(def){commands.set(def.name,def)}})}},vcs:{async get(){return{location:locationInfo,data:{branch:{current:"feature",default:"main"}}}},async status(){return{location:locationInfo,data:[]}},async branches(){return{location:locationInfo,data:[]}},async diff(){return{location:locationInfo,data:[]}}},integration:{connection:{async active(id){return{id,type:"test"}},async resolve(){return{token:"test-token"}}}}};return{ctx,hooks,tools,commands,synthetic}}
async function setup(fx,tag){const cap=JSON.parse(await fs.readFile(path.join(fx.runtime,"capabilities.json"),"utf8"));const state=makeContext(fx.project,cap);const mod=await import(`${pathToFileURL(path.join(fx.runtime,"src","index.ts")).href}?${tag}=${Date.now()}-${Math.random()}`);await mod.default.setup(state.ctx);return state}
async function authorize(state,text,sessionID="auth-session"){await state.commands.get("ade-authorize").execute({sessionID,prompt:{text}})}
function toolCtx(agent="project-manager",sessionID="tool-session"){return{sessionID,agent,messageID:"m",id:"c",async progress(){}}}
function projectPayload(status="Todo",projectId="PVT4",number=4){return {data:{user:{projectV2:{id:projectId,title:`P${number}`,fields:{nodes:[{id:"F1",name:"Status",dataType:"SINGLE_SELECT",options:[{id:"O1",name:"Todo"},{id:"O2",name:"Done"}]},{id:"F2",name:"Ready",dataType:"SINGLE_SELECT",options:[{id:"R1",name:"No"},{id:"R2",name:"Yes"}]}]},items:{pageInfo:{hasNextPage:false,endCursor:null},nodes:[{id:"ITEM1",content:{number:1,title:"I",url:"https://example.invalid/1"},fieldValues:{nodes:[{field:{name:"Status"},name:status},{field:{name:"Ready"},name:"No"}]}}]}}},organization:null}}}

// M: same prefix, different suffix must not share tracker_write grant.
test("M full tracker body participates in authorization fingerprint",async()=>{const fx=await fixture();try{const st=await setup(fx,"M");const prefix="x".repeat(220),a=prefix+"A",b=prefix+"B";await authorize(st,`ade_tracker_write ${JSON.stringify({action:"comment",external_id:"1",body:a})}`);const res=await st.tools.get("ade_tracker_write").execute({action:"comment",external_id:"1",body:b},toolCtx("tracker-operator"));const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");assert.match(v.error,/HUMAN_AUTHORIZATION_REQUIRED/)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// N: same prefix, different suffix must not share PR grant.
test("N full PR body participates in authorization fingerprint",async()=>{const fx=await fixture({gitRepo:true});try{const st=await setup(fx,"N");const prefix="p".repeat(220),a=prefix+"A",b=prefix+"B";await authorize(st,`ade_pr_create ${JSON.stringify({title:"T",body:a,base:"main"})}`);let posts=0;const orig=globalThis.fetch;globalThis.fetch=async()=>{posts++;return{ok:true,status:201,text:async()=>JSON.stringify({number:1,html_url:"https://example.invalid/pr/1"})}};try{const res=await st.tools.get("ade_pr_create").execute({title:"T",body:b,base:"main"},toolCtx("vcs-operator"));const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");assert.equal(posts,0)}finally{globalThis.fetch=orig}}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// O: tracker target/config changes after grant.
test("O tracker project target change invalidates grant before remote read or write",async()=>{const fx=await fixture();try{const st=await setup(fx,"O"),updates=[{external_id:"1",fields:[{name:"Status",value:"Done"}]}];await authorize(st,`ade_tracker_project_sync ${JSON.stringify({updates})}`);const cfg=JSON.parse(await fs.readFile(path.join(fx.project,".ai","integrations.json"),"utf8"));cfg.work_management.github.project_number=5;await fs.writeFile(path.join(fx.project,".ai","integrations.json"),JSON.stringify(cfg,null,2));let calls=0;const orig=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error("must not reach network")};try{const res=await st.tools.get("ade_tracker_project_sync").execute({updates},toolCtx());const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");assert.equal(calls,0)}finally{globalThis.fetch=orig}}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// P: staged state changes after grant.
test("P commit staged-state change invalidates grant and creates no commit",async()=>{const fx=await fixture({gitRepo:true});try{const st=await setup(fx,"P");await fs.writeFile(path.join(fx.project,"app.txt"),"authorized\n");await git(fx.project,["add","app.txt"]);await authorize(st,`ade_vcs_commit ${JSON.stringify({message:"commit authorized"})}`);const before=(await git(fx.project,["rev-parse","HEAD"])).stdout.trim();await fs.writeFile(path.join(fx.project,"app.txt"),"changed-after-grant\n");await git(fx.project,["add","app.txt"]);const res=await st.tools.get("ade_vcs_commit").execute({message:"commit authorized"},toolCtx("vcs-operator"));const v=JSON.parse(res.content),after=(await git(fx.project,["rev-parse","HEAD"])).stdout.trim();assert.equal(v.status,"BLOCKED");assert.equal(after,before)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// Q: HEAD changes after push grant.
test("Q push HEAD change invalidates grant and remote ref is not advanced",async()=>{const fx=await fixture({gitRepo:true});const bare=path.join(fx.temp,"remote.git");try{await git(fx.temp,["init","--bare",bare]);await git(fx.project,["remote","add","origin",bare]);const pol=JSON.parse(await fs.readFile(path.join(fx.project,".ai","vcs-policy.json"),"utf8"));pol.push.allowed_remote_urls=[bare];await fs.writeFile(path.join(fx.project,".ai","vcs-policy.json"),JSON.stringify(pol,null,2));const st=await setup(fx,"Q");await authorize(st,'ade_vcs_push {}');await fs.writeFile(path.join(fx.project,"new.txt"),"new\n");await git(fx.project,["add","new.txt"]);await git(fx.project,["commit","-m","after grant"]);const res=await st.tools.get("ade_vcs_push").execute({},toolCtx("vcs-operator"));const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");let remote="";try{remote=(await git(fx.temp,["--git-dir",bare,"rev-parse","refs/heads/feature"])).stdout.trim()}catch{}assert.equal(remote,"")}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// R: PR repo/base/head state change after grant.
test("R PR repository/base/head change invalidates grant before POST",async()=>{const fx=await fixture({gitRepo:true});try{const st=await setup(fx,"R");await authorize(st,`ade_pr_create ${JSON.stringify({title:"T",body:"B",base:"main"})}`);const cfg=JSON.parse(await fs.readFile(path.join(fx.project,".ai","integrations.json"),"utf8"));cfg.work_management.github.repository="other";await fs.writeFile(path.join(fx.project,".ai","integrations.json"),JSON.stringify(cfg,null,2));const pol=JSON.parse(await fs.readFile(path.join(fx.project,".ai","vcs-policy.json"),"utf8"));pol.pull_request.allowed_repositories.push("octo/other");await fs.writeFile(path.join(fx.project,".ai","vcs-policy.json"),JSON.stringify(pol,null,2));let posts=0;const orig=globalThis.fetch;globalThis.fetch=async()=>{posts++;throw new Error("must not post")};try{const res=await st.tools.get("ade_pr_create").execute({title:"T",body:"B",base:"main"},toolCtx("vcs-operator"));const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");assert.equal(posts,0)}finally{globalThis.fetch=orig}}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// S: project check definition changed after grant.
test("S project-check definition change invalidates grant before process spawn",async()=>{const fx=await fixture();try{const st=await setup(fx,"S");await authorize(st,`ade_project_check ${JSON.stringify({name:"safe"})}`);const pol=JSON.parse(await fs.readFile(path.join(fx.project,".ai","execution-policy.json"),"utf8"));pol.checks.safe.arguments=["--help"];await fs.writeFile(path.join(fx.project,".ai","execution-policy.json"),JSON.stringify(pol,null,2));const res=await st.tools.get("ade_project_check").execute({name:"safe"},toolCtx("verifier"));const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");assert.match(v.error,/HUMAN_AUTHORIZATION_REQUIRED|AUTHORIZATION_STALE/)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// T: grant store read is outside agent authority.
test("T agent read of grant store is denied",async()=>{const fx=await fixture();try{const st=await setup(fx,"T"),hook=st.hooks["permission:evaluate"],grantPath=path.join(process.platform==="win32"?process.env.LOCALAPPDATA:process.env.XDG_STATE_HOME,"opencode","ade-grants","x.jsonl");const ev={sessionID:"s",agent:"explorer",action:"read",resources:[grantPath],effect:"allow"};await hook(ev);assert.equal(ev.effect,"deny");assert.match(ev.message,/grant store/i)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// U: grant store edits/writes are outside agent authority.
test("U agent edit/write of grant store is denied",async()=>{const fx=await fixture();try{const st=await setup(fx,"U"),hook=st.hooks["permission:evaluate"],grantPath=path.join(process.platform==="win32"?process.env.LOCALAPPDATA:process.env.XDG_STATE_HOME,"opencode","ade-grants","x.jsonl");for(const action of ["edit","write"]){const ev={sessionID:"s",agent:"explorer",action,resources:[grantPath],effect:"allow"};await hook(ev);assert.equal(ev.effect,"deny");assert.match(ev.message,/grant store/i)}}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// V: order stable, semantic change sensitive.
test("V canonicalization is order-stable but semantic-change-sensitive",async()=>{const fx=await fixture();try{const st=await setup(fx,"V"),authorized=[{external_id:"1",fields:[{name:"Ready",value:"Yes"},{name:"Status",value:"Done"}]}],reordered=[{external_id:"1",fields:[{name:"Status",value:"Done"},{name:"Ready",value:"Yes"}]}];await authorize(st,`ade_tracker_project_sync ${JSON.stringify({updates:authorized})}`);let snapshot=0,mutations=0;const orig=globalThis.fetch;globalThis.fetch=async(_url,init)=>{const b=JSON.parse(init.body);if(String(b.query).includes("updateProjectV2ItemFieldValue")){mutations++;return{ok:true,status:200,text:async()=>JSON.stringify({data:{updateProjectV2ItemFieldValue:{projectV2Item:{id:"ITEM1"}}}})}}snapshot++;const p=projectPayload(snapshot>=2?"Done":"Todo");if(snapshot>=2)p.data.user.projectV2.items.nodes[0].fieldValues.nodes[1].name="Yes";return{ok:true,status:200,text:async()=>JSON.stringify(p)}};try{const ok=await st.tools.get("ade_tracker_project_sync").execute({updates:reordered},toolCtx());assert.equal(JSON.parse(ok.content).status,"TRACKER_SYNC_DONE");assert.equal(mutations,2);await authorize(st,`ade_tracker_project_sync ${JSON.stringify({updates:authorized})}`);const before=mutations;const changed=[{external_id:"1",fields:[{name:"Ready",value:"No"},{name:"Status",value:"Done"}]}];const bad=await st.tools.get("ade_tracker_project_sync").execute({updates:changed},toolCtx());assert.equal(JSON.parse(bad.content).status,"BLOCKED");assert.equal(mutations,before)}finally{globalThis.fetch=orig}}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// W: worktree content changes after stage grant.
test("W stage worktree change invalidates grant and leaves index untouched",async()=>{const fx=await fixture({gitRepo:true});try{const st=await setup(fx,"W");await fs.writeFile(path.join(fx.project,"app.txt"),"authorized-stage\n");await authorize(st,`ade_vcs_stage ${JSON.stringify({paths:["app.txt"]})}`);await fs.writeFile(path.join(fx.project,"app.txt"),"changed-after-grant\n");const res=await st.tools.get("ade_vcs_stage").execute({paths:["app.txt"]},toolCtx("vcs-operator"));const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");const staged=(await git(fx.project,["diff","--cached","--name-only"])).stdout.trim();assert.equal(staged,"")}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// X: corrupted grant store fails closed.
test("X corrupted grant store fails closed before tracker network",async()=>{const fx=await fixture();try{const st=await setup(fx,"X"),updates=[{external_id:"1",fields:[{name:"Status",value:"Done"}]}];await authorize(st,`ade_tracker_project_sync ${JSON.stringify({updates})}`);const root=path.join(process.platform==="win32"?process.env.LOCALAPPDATA:process.env.XDG_STATE_HOME,"opencode","ade-grants"),files=await fs.readdir(root),grantFile=path.join(root,files.find(x=>x.endsWith(".jsonl")));await fs.appendFile(grantFile,"{broken-json\n");let calls=0;const orig=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error("network must not be reached")};try{const res=await st.tools.get("ade_tracker_project_sync").execute({updates},toolCtx());const v=JSON.parse(res.content);assert.equal(v.status,"BLOCKED");assert.match(v.error,/GRANT_STORE_CORRUPT/);assert.equal(calls,0)}finally{globalThis.fetch=orig}}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// Y: valid push sends the exact authorized HEAD SHA.
test("Y valid push advances remote exactly to authorized HEAD",async()=>{const fx=await fixture({gitRepo:true});const bare=path.join(fx.temp,"remote-valid.git");try{await git(fx.temp,["init","--bare",bare]);await git(fx.project,["remote","add","origin",bare]);const pol=JSON.parse(await fs.readFile(path.join(fx.project,".ai","vcs-policy.json"),"utf8"));pol.push.allowed_remote_urls=[bare];await fs.writeFile(path.join(fx.project,".ai","vcs-policy.json"),JSON.stringify(pol,null,2));const st=await setup(fx,"Y"),authorized=(await git(fx.project,["rev-parse","HEAD"])).stdout.trim();await authorize(st,'ade_vcs_push {}');const res=await st.tools.get("ade_vcs_push").execute({},toolCtx("vcs-operator"));const v=JSON.parse(res.content);assert.equal(v.status,"VCS_PUSHED");assert.equal(v.sha,authorized);const remote=(await git(fx.temp,["--git-dir",bare,"rev-parse","refs/heads/feature"])).stdout.trim();assert.equal(remote,authorized)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// Z: valid project-check grant executes the exact unchanged definition.
test("Z valid project-check grant executes unchanged definition",async()=>{const fx=await fixture();try{const st=await setup(fx,"Z");await authorize(st,`ade_project_check ${JSON.stringify({name:"safe"})}`);const res=await st.tools.get("ade_project_check").execute({name:"safe"},toolCtx("verifier"));const v=JSON.parse(res.content);assert.equal(v.status,"PROJECT_CHECK_VALIDATED");assert.equal(v.exit_code,0)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// AA: environment-controlled grant store must never be located inside the project.
test("AA grant store redirected inside project is rejected",async()=>{const fx=await fixture();try{const st=await setup(fx,"AA");if(process.platform==="win32")process.env.LOCALAPPDATA=path.join(fx.project,"local-state");else process.env.XDG_STATE_HOME=path.join(fx.project,"local-state");await authorize(st,`ade_tracker_project_sync ${JSON.stringify({updates:[{external_id:"1",fields:[{name:"Status",value:"Done"}]}]})}`);const msg=String(st.synthetic.at(-1)?.text||"");assert.match(msg,/ADE_AUTHORIZE_BLOCKED/);assert.match(msg,/GRANT_STORE_UNSAFE/)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})

// AB: grant root must not traverse a symlink/junction in its parent chain.
test("AB grant store parent symlink is rejected",async()=>{const fx=await fixture();try{const actual=path.join(fx.temp,"actual-state");const link=path.join(fx.temp,"linked-state");await fs.mkdir(actual,{recursive:true});let linked=true;try{await fs.symlink(actual,link,process.platform==="win32"?"junction":"dir")}catch{linked=false}if(!linked)return;const st=await setup(fx,"AB");if(process.platform==="win32")process.env.LOCALAPPDATA=link;else process.env.XDG_STATE_HOME=link;await authorize(st,`ade_tracker_project_sync ${JSON.stringify({updates:[{external_id:"1",fields:[{name:"Status",value:"Done"}]}]})}`);const msg=String(st.synthetic.at(-1)?.text||"");assert.match(msg,/ADE_AUTHORIZE_BLOCKED/);assert.match(msg,/GRANT_STORE_UNSAFE/)}finally{fx.restoreEnv();await fs.rm(fx.temp,{recursive:true,force:true})}})
