import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { pathToFileURL, fileURLToPath } from "node:url"

async function copyTree(src,dst){await fs.cp(src,dst,{recursive:true})}
async function fixture(){
  const pluginDir=path.resolve(fileURLToPath(new URL("..",import.meta.url))),temp=await fs.mkdtemp(path.join(os.tmpdir(),"ade-v6-life-")),runtime=path.join(temp,"plugin"),project=path.join(temp,"project")
  await fs.mkdir(path.join(runtime,"src"),{recursive:true});for(const f of ["src/index.ts","capabilities.json"])await fs.copyFile(path.join(pluginDir,f),path.join(runtime,f));await copyTree(path.join(pluginDir,"assets"),path.join(runtime,"assets"));await copyTree(path.join(pluginDir,"compat-runtime"),path.join(runtime,"compat-runtime"))
  const sdk=path.join(runtime,"node_modules","@opencode-ai","plugin");await fs.mkdir(sdk,{recursive:true});await fs.writeFile(path.join(sdk,"package.json"),JSON.stringify({name:"@opencode-ai/plugin",type:"module",exports:"./index.js"}));await fs.writeFile(path.join(sdk,"index.js"),"export const Plugin={define:(value)=>value}\n")
  await fs.mkdir(path.join(project,".ai"),{recursive:true});await fs.writeFile(path.join(project,".ai","control.json"),JSON.stringify({schema_version:3,work_item_id:"LIFE",profile:"STANDARD",revision:0,global_status:"NOT_DONE",product:{required:false,status:"DRAFT",revision:0},delivery:{required:false,status:"DRAFT",revision:0},engineering:{required:true,status:"DISCOVERING",revision:0},evidence:[],evidence_count:0,recent_handoffs:[],notes:[],work_management:{provider:"none",sync_status:"NOT_CONFIGURED",last_sync_at:"",external_refs:[]},traceability:{file:".ai/traceability.json"},audit:{file:".ai/audit.jsonl"}},null,2)+"\n")
  const oldL=process.env.LOCALAPPDATA,oldX=process.env.XDG_STATE_HOME;process.env.LOCALAPPDATA=path.join(temp,"local");process.env.XDG_STATE_HOME=path.join(temp,"xdg")
  return{temp,runtime,project,restore(){if(oldL==null)delete process.env.LOCALAPPDATA;else process.env.LOCALAPPDATA=oldL;if(oldX==null)delete process.env.XDG_STATE_HOME;else process.env.XDG_STATE_HOME=oldX}}
}
function context(project,cap){const hooks={},tools=new Map(),commands=new Map(),sessions=new Map([["root",{id:"root",location:{directory:project},model:{providerID:"opencode",id:"muse-spark-1.2-contributor-free"},messages:[]}]]);let seq=0,defaultAgent;const agents=Object.keys(cap.agents).map(id=>({id,description:id})),location={directory:project,project:{id:"p",directory:project,canonical:project}};const ctx={app:{version:"0.0.0-beta-test"},location,storage:{async set(){},async get(){},async remove(){},async scan(){return{entries:[]}}},agent:{async transform(cb){cb({get(id){return agents.find(a=>a.id===id)},list(){return agents},default(id){defaultAgent=id},update(){},remove(){}})},async list(){return{location,data:agents}}},skill:{async list(){return{location,data:[{id:"ai-driven-engineering"}]}}},plugin:{async list(){return{location,data:[{id:"ai-driven-engineering.native"}]}}},session:{async create(){const id=`w${++seq}`;sessions.set(id,{id,location:{directory:project},messages:[]});return sessions.get(id)},async get({sessionID}){return sessions.get(sessionID)||{id:sessionID,location:{directory:project}}},async hook(n,cb){hooks[`session:${n}`]=cb},async switchAgent({sessionID,agent}){sessions.get(sessionID).agent=agent},async switchModel(){},async prompt({id,sessionID,text,delivery="steer"}){const messageID=id||`msg-user-${sessionID}`;const session=sessions.get(sessionID);session.messages=[{id:messageID,type:"user",time:{created:Date.now()},text:String(text||"")}];return{id:messageID,sessionID,type:"user",delivery}},async wait({sessionID}){const session=sessions.get(sessionID);if(session){session.outcome="succeeded";session.tokens={input:10,output:2,reasoning:0};session.messages.push({id:`msg-assistant-${sessionID}`,type:"assistant",agent:session.agent||"explorer",model:{providerID:"opencode",id:"muse-spark-1.2-contributor-free"},time:{created:Date.now(),completed:Date.now()},content:[{type:"text",text:"ok"}],finish:"stop"})}},async context({sessionID}){return sessions.get(sessionID)?.messages||[]},async interrupt(){},async synthetic(){}},permission:{async hook(n,cb){hooks[`permission:${n}`]=cb}},tool:{async transform(cb){cb({add(def){const ns=def.options?.namespace?`${def.options.namespace}_`:"";tools.set(`${ns}${def.name}`,def)},list(){return[...tools.values()]},get(id){return tools.get(id)},update(){},remove(id){tools.delete(id)}})}},command:{async transform(cb){cb({add(def){commands.set(def.name,def)}})}},vcs:{async get(){return{location,data:{branch:{current:"feature",default:"main"}}}},async status(){return{location,data:[]}},async branches(){return{location,data:[]}},async diff(){return{location,data:[]}}},integration:{connection:{async active(){return null},async resolve(){return null}}}};return{ctx,hooks,tools,commands,get defaultAgent(){return defaultAgent}}}
const tctx={sessionID:"root",agent:"orchestrator",messageID:"m",id:"c",async progress(){}}

test("OpenCode V2-shaped v6 lifecycle loads kernel surface",async()=>{const fx=await fixture();try{const cap=JSON.parse(await fs.readFile(path.join(fx.runtime,"capabilities.json"),"utf8")),state=context(fx.project,cap),mod=await import(`${pathToFileURL(path.join(fx.runtime,"src","index.ts")).href}?life=${Date.now()}`);assert.equal(mod.default.id,"ai-driven-engineering.native");const cleanup=await mod.default.setup(state.ctx);assert.equal(state.defaultAgent,"orchestrator");assert.equal(state.tools.size,34);assert.ok(state.commands.size>=10);const hook=state.hooks["session:context"],all=Object.fromEntries([...state.tools.keys()].map(n=>[n,{}]));all.subagent={};all.shell={};all.edit={};const event={sessionID:"root",agent:"orchestrator",model:{},system:[],messages:[],tools:all,generation:{}};await hook(event);assert.deepEqual(new Set(Object.keys(event.tools)),new Set(cap.agents.orchestrator));const status=JSON.parse((await state.tools.get("ade_status").execute({},tctx)).content);assert.equal(status.plugin.version,"6.1.0");assert.equal(status.canonical_state,"hash-chained-event-journal");assert.equal(status.legacy_import.authoritative,false);const start=JSON.parse((await state.tools.get("ade_workflow_start").execute({objective:"inspect",kind:"analysis",risk:"LOW"},tctx)).content);assert.equal(start.workflow.status,"RUNNING");const run=JSON.parse((await state.tools.get("ade_workflow_run").execute({workflow_id:start.workflow.id,max_jobs:4},tctx)).content);assert.equal(run.workflow.status,"DONE");const perm=state.hooks["permission:evaluate"],ev={sessionID:"root",agent:"orchestrator",action:"subagent",resources:["general"],effect:"allow"};await perm(ev);assert.equal(ev.effect,"deny");if(typeof cleanup==="function")await cleanup()}finally{fx.restore();await fs.rm(fx.temp,{recursive:true,force:true})}})

test("beta SDK without named Plugin export still loads raw default contract",async()=>{const fx=await fixture();try{await fs.writeFile(path.join(fx.runtime,"node_modules","@opencode-ai","plugin","index.js"),"export default {}\n");const cap=JSON.parse(await fs.readFile(path.join(fx.runtime,"capabilities.json"),"utf8")),state=context(fx.project,cap),mod=await import(`${pathToFileURL(path.join(fx.runtime,"src","index.ts")).href}?raw=${Date.now()}`);await mod.default.setup(state.ctx);assert.equal(state.tools.size,34)}finally{fx.restore();await fs.rm(fx.temp,{recursive:true,force:true})}})
