import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"

const cap=JSON.parse(fs.readFileSync(new URL("../capabilities.json",import.meta.url)))
const pkg=JSON.parse(fs.readFileSync(new URL("../package.json",import.meta.url)))
const src=fs.readFileSync(new URL("../src/index.ts",import.meta.url),"utf8")
const tools=Object.keys(cap.tools)

test("v6 registry is kernel-centric",()=>{assert.equal(cap.version,"6.0.11");assert.equal(Object.keys(cap.agents).length,5);assert.equal(tools.length,34);for(const t of ["ade_workflow_start","ade_workflow_run","ade_workflow_snapshot","ade_workflow_cancel","ade_kernel_reconcile","ade_kernel_events"])assert.ok(tools.includes(t),t);assert.equal(cap.durable_kernel.runtime,"file_backed_event_sourcing")})
test("orchestrator submits intent but cannot delegate or mutate code",()=>{const a=cap.agents.orchestrator;assert.ok(a.includes("ade_workflow_start")&&a.includes("ade_workflow_run"));assert.ok(!a.includes("ade_delegate"));assert.ok(!a.includes("ade_vcs_commit"));assert.ok(cap.hide_core_tools.orchestrator.includes("subagent"));assert.ok(cap.hide_core_tools.orchestrator.includes("edit"));assert.ok(cap.hide_core_tools.orchestrator.includes("shell"))})
test("workers are disposable and never coordinate workers",()=>{for(const a of ["explorer","implementer","verifier","reviewer"]){assert.ok(cap.hide_core_tools[a].includes("subagent"));assert.ok(!cap.agents[a].includes("ade_workflow_start"));assert.ok(!cap.agents[a].includes("ade_workflow_run"))}assert.deepEqual(cap.durable_kernel.worker_roles,{ANALYST:"explorer",BUILDER:"implementer",VERIFIER:"verifier",REVIEWER:"reviewer"})})
test("builder is the only active editing worker",()=>{assert.ok(!cap.hide_core_tools.implementer.includes("edit"));for(const a of ["explorer","verifier","reviewer"])assert.ok(cap.hide_core_tools[a].includes("edit"),a)})
test("generation budgets are bounded for every active agent",()=>{assert.deepEqual(new Set(Object.keys(cap.generation_max_tokens)),new Set(Object.keys(cap.agents)));for(const n of Object.values(cap.generation_max_tokens))assert.ok(Number.isInteger(n)&&n>=500&&n<=2000)})
test("OpenCode V2 Promise plugin contract remains explicit",()=>{assert.ok(src.includes('import * as OpenCodePlugin from "@opencode-ai/plugin"'));assert.ok(src.includes("raw-default-compat"));assert.ok(src.includes("export default pluginDefine({"));assert.equal(pkg.exports,"./index.ts");assert.equal(fs.readFileSync(new URL("../index.ts",import.meta.url),"utf8").trim(),'// OpenCode V2 resolves configured plugin directories from this root entrypoint.\nexport { default } from "./src/index.ts"')})
test("durable event journal is hash chained and snapshot is derived",()=>{for(const marker of ["KERNEL_SCHEMA_VERSION","events.jsonl","snapshot.json","prev_hash","event_hash","kernelReadEvents","kernelReduceEvent","kernelAppendDrafts","ADE_KERNEL_CORRUPT"])assert.ok(src.includes(marker),marker);assert.ok(src.includes("sha256Hex(canonicalStringify(kernelEventHashMaterial(ev)))"))})
test("kernel store is external and protected from agents",()=>{for(const marker of ["kernelBaseDir","assertGrantStoreSafeForProject","resourceTouchesKernelStore","ADE_KERNEL_STORE_UNSAFE","durable kernel store is outside agent authority"])assert.ok(src.includes(marker),marker);assert.ok(src.includes('path.join(base,"opencode","ade-kernel")'))})
test("workflow state machine requires deterministic verification for engineering",()=>{assert.ok(src.includes('kind==="engineering"&&!checks.length'));assert.ok(src.includes("ADE_WORKFLOW_VERIFICATION_REQUIRED"));assert.ok(src.includes("RESULT_PROPOSED"));assert.ok(src.includes("WAITING_APPROVAL"))})
test("scheduler owns worker sessions and waits synchronously",()=>{for(const marker of ["kernelWorkerSession","ctx.session.create","ctx.session.switchAgent","ctx.session.prompt","waitWorkerWithTimeout","ctx.session.context"])assert.ok(src.includes(marker),marker);assert.ok(src.includes("only the durable kernel scheduler may create worker sessions"))})
test("worker execution has leases, bounded attempts, and reconciliation",()=>{for(const marker of ["KERNEL_JOB_LEASE_MS","KERNEL_JOB_MAX_ATTEMPTS","lease_expires_at","kernelReconcile","WORKER_LEASE_EXPIRED"])assert.ok(src.includes(marker),marker);assert.equal(cap.deterministic_control_plane.job_max_attempts,2)})
test("mutating builder jobs are project-serialized and reject dirty baselines",()=>{assert.ok(src.includes("mutation.lock"));assert.ok(src.includes("ADE_KERNEL_DIRTY_WORKTREE"));assert.ok(src.includes("withFileLock(kp.mutationLock"))})
test("tracker sync can run as a deterministic kernel activity",()=>{assert.ok(src.includes('job.type==="TRACKER_SYNC"'));assert.ok(src.includes('consumeHumanGrant(root,"ade_tracker_project_sync"'));assert.ok(src.includes("executeProjectSync(input"));assert.equal(cap.deterministic_control_plane.tracker_primary[1],"tracker_sync workflow")})
test("engineering checks consume exact external grants inside kernel activity",()=>{assert.ok(src.includes("kernelRunVerificationChecks"));assert.ok(src.includes('consumeHumanGrant(root,"ade_project_check"'));assert.ok(src.includes("nativeProjectCheck(root"))})
test("legacy delegation is physically absent from the v6 tool surface",()=>{assert.ok(!tools.includes("ade_delegate"));assert.ok(!src.includes("managedDelegateExecute"));assert.ok(!src.includes("DELEGATION_DAG"));for(const a of Object.values(cap.agents))assert.ok(!a.includes("ade_delegate"))})
test("provider tool_choice compatibility and retry circuit breaker are preserved",()=>{assert.ok(src.includes('ctx.session.hook("http.request"'));assert.ok(src.includes('ctx.session.hook("retry"'));for(const marker of ["auto_only_tool_choice_models","tool_choice:auto-only","reasoning item expired","seen===0","seen>0"])assert.ok(src.includes(marker),marker)})
test("exact-effect authorization hardening is preserved",()=>{for(const marker of ["EXPLICIT_EXTERNAL_GRANT","ADE_AUTHORIZATION_STALE","resourceFingerprintFor","consumeHumanGrant","assertAuthorizationUnchanged","GRANT_MAX_USES = 1"])assert.ok(src.includes(marker),marker)})
test("VCS hardening is preserved",()=>{for(const marker of ["assertNoSecretStaged","--no-verify","allowed_remote_urls","ls-remote","authorized HEAD","commit.gpgSign=false"]) { if(marker==="commit.gpgSign=false") assert.ok(!src.includes(marker)); else assert.ok(src.includes(marker),marker)}})
test("process and Docker hardening is preserved",()=>{for(const marker of ["minimalEnv","--network","--read-only","--cap-drop","ALL","no-new-privileges","pids-limit"])assert.ok(src.includes(marker),marker)})
test("active ADE agents hide raw shell",()=>{for(const a of Object.keys(cap.agents))assert.ok(cap.hide_core_tools[a].includes("shell"),a)})

test("beta-18721 worker contract remains structurally strict",()=>{assert.ok(src.includes('canonicalSystemTextPart'));assert.ok(src.includes('sessionAssistantSettled'));assert.ok(src.includes('WORKER_EXECUTION_FAILED'));assert.ok(src.includes('WORKER_INTERRUPTED'));assert.ok(src.includes('WORKER_INVALID_OUTPUT'));assert.ok(!/event\.system\.push\(\{\s*text\s*:/.test(src))})
